# group_vars/project.ansibled.yml
# ---
# specify VPC details and AWS credentials

# general details about our VPC
vpc_name: ansibled-vpc
vpc_key: ansibled-key
vpc_dns_zone: ansibled
vpc_use_nat: false

# credentials for AWS (no, they aren't real...)
aws_region: ap-southeast-2
aws_account_id: "{{ aws_account_id }}"
aws_access_key: "{{ aws_access_key }}"
aws_secret_key: "{{ aws_secret_key }}"

# Logentries REST API key -- read/write
logentries_api_key: "{{ logentries_api_key }}"
