# host_vars/vpc.ansibled.yml

vpc_cidr_block: 172.32.0.0/16

vpc_subnets:
  private-a:
    cidr: 172.32.1.0/24
    az: "{{ aws_region }}a"
  public-a:
    cidr: 172.32.2.0/24
    az: "{{ aws_region }}a"
  private-b:
    cidr: 172.32.3.0/24
    az: "{{ aws_region }}b"
  public-b:
    cidr: 172.32.4.0/24
    az: "{{ aws_region }}b"
  private-c:
    cidr: 172.32.5.0/24
    az: "{{ aws_region }}c"
  public-c:
    cidr: 172.32.6.0/24
    az: "{{ aws_region }}c"

vpc_security_groups:
  - name: vpc
    description: "Allow internal traffic in the VPC"
    rules:
      - proto: all
        group_name: vpc
        ports: all
  - name: allow-public-ssh
    description: "Allow public SSH"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: allow-public-http
    description: "Allow public web traffic"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80
          - 8080
          - 443
